from pydantic import BaseModel, Field


class PredictRequest(BaseModel):
    model_config = {
        "json_schema_extra": {
            "example": {
                "request_id": "550e8400-e29b-41d4-a716-446655440000",
                "deck_card_ids": [26000000, 26000001, 26000002, 26000003, 26000004, 26000005, 26000006, 159000000],
                "deck_card_levels": [14, 13, 13, 13, 13, 11, 11, 14],
                "deck_evo_levels": [1, 0, 0, 0, 0, 0, 0, 0],
                "opponent_card_ids": [26000010, 26000011, 26000012, 26000013, 26000014, 26000015, 26000016, 159000000],
                "opponent_card_levels": [13, 13, 13, 13, 12, 12, 11, 14],
                "opponent_evo_levels": [0, 0, 0, 0, 0, 0, 0, 0],
                "battle_type": "pathOfLegend",
                "league_number": 7,
                "starting_trophies": None
            }
        }
    }

    request_id: str = Field(..., description="UUID generated by Spring Boot for distributed tracing")
    deck_card_ids: list[int] = Field(..., min_length=8, max_length=9)
    deck_card_levels: list[int] = Field(..., min_length=8, max_length=9)
    deck_evo_levels: list[int] = Field(..., min_length=8, max_length=9)
    opponent_card_ids: list[int] = Field(..., min_length=8, max_length=9)
    opponent_card_levels: list[int] = Field(..., min_length=8, max_length=9)
    opponent_evo_levels: list[int] = Field(..., min_length=8, max_length=9)
    battle_type: str = Field("pathOfLegend", description="pathOfLegend | ladder")
    league_number: int | None = Field(None, description="PoL league (0-10). Required for pathOfLegend.")
    starting_trophies: int | None = Field(None, description="Starting trophies. Required for ladder.")


class PredictResponse(BaseModel):
    model_config = {
        "json_schema_extra": {
            "example": {
                "request_id": "550e8400-e29b-41d4-a716-446655440000",
                "win_probability": 0.6234,
                "model_version": "lgbm-pathOfLegend-20260401120000"
            }
        }
    }

    request_id: str
    win_probability: float
    model_version: str | None
