from pydantic import BaseModel, Field


class PredictRequest(BaseModel):
    request_id: str = Field(..., description="UUID generated by Spring Boot for distributed tracing")
    deck_card_ids: list[int] = Field(..., min_length=8, max_length=9)
    deck_card_levels: list[int] = Field(..., min_length=8, max_length=9)
    deck_evo_levels: list[int] = Field(..., min_length=8, max_length=9)
    opponent_card_ids: list[int] = Field(..., min_length=8, max_length=9)
    opponent_card_levels: list[int] = Field(..., min_length=8, max_length=9)
    opponent_evo_levels: list[int] = Field(..., min_length=8, max_length=9)
    battle_type: str = "pathOfLegend"
    league_number: int | None = None
    starting_trophies: int | None = None


class PredictResponse(BaseModel):
    request_id: str
    win_probability: float
    model_version: str | None
